# Generated by Django 5.0.7 on 2024-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_user_options_user_unique_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_phone_number',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username',), name='allow_username_null', nulls_distinct=True),
        ),
    ]
