# Generated by Django 5.0.7 on 2024-08-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_category_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='href',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
        migrations.AddField(
            model_name='theme',
            name='href',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
