# Generated by Django 5.0.7 on 2024-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_href_theme_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='href',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='href',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
