# Generated by Django 5.0.7 on 2024-08-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_comment_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
