# Generated by Django 5.0.7 on 2024-08-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
