# Generated by Django 5.0.7 on 2024-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_reservation_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
