# Generated by Django 5.0.7 on 2024-09-13 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 13, 17, 49, 0, 134867, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
