# Generated by Django 5.0.7 on 2024-09-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_banned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
