# Generated by Django 5.0.7 on 2024-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_article_cover_alter_theme_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='article_pics'),
        ),
    ]
