# Generated by Django 5.0.7 on 2024-10-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
