# Generated by Django 5.0.7 on 2024-10-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_theme_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=0, max_digits=3)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.theme')),
            ],
        ),
    ]
