# Generated by Django 5.0.7 on 2025-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_off_code_off_createdat_off_creator_off_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=None, null=True, upload_to='category/'),
        ),
    ]
