# Generated by Django 5.0.7 on 2025-03-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_category_image_category_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
