# Generated by Django 5.0.7 on 2025-03-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
